version: '3.7'

services:
  ui:
    tty: true
    stdin_open: true
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
